# @package _global_

defaults:
  - /model: facebook_dinov3-vitl16
  - _self_

mode: train

# ---- Hydra output directory settings ----
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${model.method}_${model.id_wo_slash}

# ---- Common paths ----
save_dir: ${hydra:run.dir}/checkpoints/

# ---- Train-specific settings ----
train:
  epoch: 15
  learning_rate: 0.001
  batch_size: 8
  scheduler:
    # type: CosineAnnealingLR
    # params:
    #   T_max: ${train.epoch}
    #   eta_min: 1e-6
  ema:
    enabled: true
    decay: 0.999
    use_buffers: false
    warmup_steps: 100

save_freq: 1
print_freq: 1
